[packages.flan-cli]
versioned_files = [
  "cli/Cargo.toml",
  { path = "xtask/Cargo.toml", dependency = "flan-cli" },
  "Cargo.lock",
]
scopes = ["cli"]
changelog = "cli/CHANGELOG.md"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = 'git commit -m "chore: prepare releases"'

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "taskylizard"
repo = "flan"
